apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green
  namespace: default
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: blue-green-service
      previewService: blue-green-service-preview
      autoPromotionSeconds: 0
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
        - name: blue-green
          image: ysufemrlty/my-basic-app:latest
