apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  namespace: flask
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: my-app-service
      previewService: my-app-preview-service
      autoPromotionSeconds: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ysufemrlty/my-basic-app:latest
