apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  namespace: default
  labels:
    app: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green
      version: blue
  template:
    metadata:
      labels:
        app: blue-green
        version: blue
    spec:
      containers:
        - name: blue-green
          image: ysufemrlty/my-basic-app:v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  namespace: default
  labels:
    app: blue-green
spec:
  replicas: 0  # initially no replicas, will scale when switching to green
  selector:
    matchLabels:
      app: blue-green
      version: green
  template:
    metadata:
      labels:
        app: blue-green
        version: green
    spec:
      containers:
        - name: blue-green
          image: ysufemrlty/case24
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: default
spec:
  selector:
    app: blue-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30090
  type: NodePort
