apiVersion: v1
kind: Service
metadata:
  name: blue-green-service-preview
  namespace: default
spec:
  selector:
    app: blue-green
    version: preview  # Burada versiyon değişikliğini yapıyoruz, green'e yönlendiriyoruz.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30092
  type: NodePort
