apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: default
spec:
  selector:
    app: blue-green
    version: green  # Burada versiyon değişikliğini yapıyoruz, green'e yönlendiriyoruz.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30091
  type: NodePort
